apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: app-secrets
    envs:
      - .env

configMapGenerator:
  - name: backend-config
    files:
      - config.toml=internal/config/config.toml

  - name: parsers-config
    files:
      - config.toml=parsers/src/parsers/config/config.toml

resources:
    - k8s/infra/postgres.yaml
    - k8s/infra/rabbitmq.yaml
    - k8s/infra/monitoring.yaml

    - k8s/apps/parsers.yaml
    - k8s/apps/processing.yaml
    - k8s/apps/delivery.yaml
    - k8s/apps/bot.yaml
