[project]
name = "parsers"
version = "0.1.0"
description = "Microservice for arbitrage"
requires-python = ">=3.13"
dependencies = [
    "aio-pika",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "logger>=1.4",
    "loguru>=0.7.3",
    "opentelemetry-distro>=0.65b0",
    "opentelemetry-exporter-otlp>=1.44.0",
    "opentelemetry-instrumentation-aio-pika>=0.65b0",
    "opentelemetry-instrumentation-asyncio>=0.65b0",
    "opentelemetry-instrumentation-grpc>=0.65b0",
    "opentelemetry-instrumentation-httpx>=0.65b0",
    "opentelemetry-instrumentation-logging>=0.65b0",
    "opentelemetry-instrumentation-requests>=0.65b0",
    "pydantic",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-mock>=3.15.1",
    "python-dotenv>=1.2.2",
    "ruff>=0.16.0",
]

[tool.uv]
package = true

[tool.uv.sources]
parsers = { workspace = true }
