services:
    postgres-db:
        image: postgres:17-alpine
        container_name: postgres-nxe
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PWD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql

    rabbitmq:
        image: rabbitmq:4-management-alpine
        container_name: rabbitmq-nxe
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBIT_PWD}
        ports:
            - "${RABBIT_PORT}:5672"
            - "${RABBIT_MP}:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

    delivery-go:
        build:
            context: ../
            dockerfile: cmd/delivery/Dockerfile
        container_name: delivery-nxe
        ports:
            - "50051:50051"
        environment:
            - TELEGRAM_BOT_API=${TELEGRAM_BOT_API}

    processing-go:
        build:
            context: ../
            dockerfile: cmd/processing/Dockerfile
        container_name: processing-nxe
        environment:
            - DB_USER=${DB_USER}
            - DB_PWD=${DB_PWD}
            - DB_NAME=${DB_NAME}
            - DB_HOST=postgres-db
            - DB_PORT=5432
            - RABBIT_HOST=rabbitmq-nxe
            - RABBIT_USER=${RABBIT_USER}
            - RABBIT_PWD=${RABBIT_PWD}
            - RABBIT_PORT=5672
            - RABBIT_MP=15672
        depends_on:
            - rabbitmq
            - postgres-db
            - delivery-go
        ports:
            - "50050:50050"

    bot-go:
        build:
            context: ../
            dockerfile: cmd/bot/Dockerfile
        container_name: bot-go-nxe
        environment:
            - TELEGRAM_BOT_API=${TELEGRAM_BOT_API}
            - DB_USER=${DB_USER}
            - DB_PWD=${DB_PWD}
            - DB_NAME=${DB_NAME}
            - DB_HOST=postgres-db
            - DB_PORT=5432
        depends_on:
            - postgres-db
            - processing-go

    parsers-py:
        build:
            context: ../parsers/
            dockerfile: Dockerfile
        container_name: parsers-py-nxe
        environment:
            - RABBIT_HOST=rabbitmq-nxe
            - RABBIT_USER=${RABBIT_USER}
            - RABBIT_PWD=${RABBIT_PWD}
            - RABBIT_PORT=5672
            - RABBIT_MP=15672
        depends_on:
            - rabbitmq

volumes:
    postgres_data:
    rabbitmq_data:
