// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.2
// source: internal/transport/proto/messages.proto

package transport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_SendUser_FullMethodName = "/messages.DataService/SendUser"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	SendUser(ctx context.Context, in *AlertNotification, opts ...grpc.CallOption) (*Ack, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) SendUser(ctx context.Context, in *AlertNotification, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, DataService_SendUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	SendUser(context.Context, *AlertNotification) (*Ack, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) SendUser(context.Context, *AlertNotification) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendUser not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_SendUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).SendUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_SendUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).SendUser(ctx, req.(*AlertNotification))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messages.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendUser",
			Handler:    _DataService_SendUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/transport/proto/messages.proto",
}

const (
	ProcessingService_ReloadSubscriptions_FullMethodName = "/messages.ProcessingService/ReloadSubscriptions"
)

// ProcessingServiceClient is the client API for ProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessingServiceClient interface {
	ReloadSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReloadSubscriptionsResponse, error)
}

type processingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessingServiceClient(cc grpc.ClientConnInterface) ProcessingServiceClient {
	return &processingServiceClient{cc}
}

func (c *processingServiceClient) ReloadSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReloadSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadSubscriptionsResponse)
	err := c.cc.Invoke(ctx, ProcessingService_ReloadSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessingServiceServer is the server API for ProcessingService service.
// All implementations must embed UnimplementedProcessingServiceServer
// for forward compatibility.
type ProcessingServiceServer interface {
	ReloadSubscriptions(context.Context, *emptypb.Empty) (*ReloadSubscriptionsResponse, error)
	mustEmbedUnimplementedProcessingServiceServer()
}

// UnimplementedProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessingServiceServer struct{}

func (UnimplementedProcessingServiceServer) ReloadSubscriptions(context.Context, *emptypb.Empty) (*ReloadSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadSubscriptions not implemented")
}
func (UnimplementedProcessingServiceServer) mustEmbedUnimplementedProcessingServiceServer() {}
func (UnimplementedProcessingServiceServer) testEmbeddedByValue()                           {}

// UnsafeProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessingServiceServer will
// result in compilation errors.
type UnsafeProcessingServiceServer interface {
	mustEmbedUnimplementedProcessingServiceServer()
}

func RegisterProcessingServiceServer(s grpc.ServiceRegistrar, srv ProcessingServiceServer) {
	// If the following call panics, it indicates UnimplementedProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessingService_ServiceDesc, srv)
}

func _ProcessingService_ReloadSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServiceServer).ReloadSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessingService_ReloadSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServiceServer).ReloadSubscriptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessingService_ServiceDesc is the grpc.ServiceDesc for ProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messages.ProcessingService",
	HandlerType: (*ProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReloadSubscriptions",
			Handler:    _ProcessingService_ReloadSubscriptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/transport/proto/messages.proto",
}
