syntax = "proto3";
package messages;
import "google/protobuf/empty.proto";
option go_package = "github.com/Noxie-Arbitrage/internal/transport/";

service DataService {
    rpc SendUser(AlertNotification) returns (Ack);
}
service ProcessingService {
    rpc ReloadSubscriptions(google.protobuf.Empty) returns (ReloadSubscriptionsResponse);
}

message AlertNotification {
    int64 telegram_chat_id = 1;
    string text = 2;
}

message Ack {
    bool status = 1;
    string details = 2;
}

message ReloadSubscriptionsResponse {
    bool status = 1;
}
