// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.2
// source: internal/transport/proto/messages.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TelegramChatId int64                  `protobuf:"varint,1,opt,name=telegram_chat_id,json=telegramChatId,proto3" json:"telegram_chat_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlertNotification) Reset() {
	*x = AlertNotification{}
	mi := &file_internal_transport_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertNotification) ProtoMessage() {}

func (x *AlertNotification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertNotification.ProtoReflect.Descriptor instead.
func (*AlertNotification) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *AlertNotification) GetTelegramChatId() int64 {
	if x != nil {
		return x.TelegramChatId
	}
	return 0
}

func (x *AlertNotification) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_internal_transport_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Ack) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ReloadSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadSubscriptionsResponse) Reset() {
	*x = ReloadSubscriptionsResponse{}
	mi := &file_internal_transport_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadSubscriptionsResponse) ProtoMessage() {}

func (x *ReloadSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ReloadSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ReloadSubscriptionsResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_internal_transport_proto_messages_proto protoreflect.FileDescriptor

const file_internal_transport_proto_messages_proto_rawDesc = "" +
	"\n" +
	"'internal/transport/proto/messages.proto\x12\bmessages\x1a\x1bgoogle/protobuf/empty.proto\"Q\n" +
	"\x11AlertNotification\x12(\n" +
	"\x10telegram_chat_id\x18\x01 \x01(\x03R\x0etelegramChatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"7\n" +
	"\x03Ack\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails\"5\n" +
	"\x1bReloadSubscriptionsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2E\n" +
	"\vDataService\x126\n" +
	"\bSendUser\x12\x1b.messages.AlertNotification\x1a\r.messages.Ack2i\n" +
	"\x11ProcessingService\x12T\n" +
	"\x13ReloadSubscriptions\x12\x16.google.protobuf.Empty\x1a%.messages.ReloadSubscriptionsResponseB0Z.github.com/Noxie-Arbitrage/internal/transport/b\x06proto3"

var (
	file_internal_transport_proto_messages_proto_rawDescOnce sync.Once
	file_internal_transport_proto_messages_proto_rawDescData []byte
)

func file_internal_transport_proto_messages_proto_rawDescGZIP() []byte {
	file_internal_transport_proto_messages_proto_rawDescOnce.Do(func() {
		file_internal_transport_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_proto_messages_proto_rawDesc), len(file_internal_transport_proto_messages_proto_rawDesc)))
	})
	return file_internal_transport_proto_messages_proto_rawDescData
}

var file_internal_transport_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_transport_proto_messages_proto_goTypes = []any{
	(*AlertNotification)(nil),           // 0: messages.AlertNotification
	(*Ack)(nil),                         // 1: messages.Ack
	(*ReloadSubscriptionsResponse)(nil), // 2: messages.ReloadSubscriptionsResponse
	(*emptypb.Empty)(nil),               // 3: google.protobuf.Empty
}
var file_internal_transport_proto_messages_proto_depIdxs = []int32{
	0, // 0: messages.DataService.SendUser:input_type -> messages.AlertNotification
	3, // 1: messages.ProcessingService.ReloadSubscriptions:input_type -> google.protobuf.Empty
	1, // 2: messages.DataService.SendUser:output_type -> messages.Ack
	2, // 3: messages.ProcessingService.ReloadSubscriptions:output_type -> messages.ReloadSubscriptionsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_proto_messages_proto_init() }
func file_internal_transport_proto_messages_proto_init() {
	if File_internal_transport_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_proto_messages_proto_rawDesc), len(file_internal_transport_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_transport_proto_messages_proto_goTypes,
		DependencyIndexes: file_internal_transport_proto_messages_proto_depIdxs,
		MessageInfos:      file_internal_transport_proto_messages_proto_msgTypes,
	}.Build()
	File_internal_transport_proto_messages_proto = out.File
	file_internal_transport_proto_messages_proto_goTypes = nil
	file_internal_transport_proto_messages_proto_depIdxs = nil
}
